name: Sync Upstream (Rebase, No Merge Commits)

on:
  schedule:
    - cron: "0 3 * * 1"   # 每周一 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0   # 需要完整历史，才能 rebase/fast-forward

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/qemu/qemu.git
          git fetch upstream --prune --tags

      - name: Sync all upstream branches
        run: |
          for remote_branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/upstream/*); do
            branch=${remote_branch#upstream/}
            echo "==> Syncing branch: $branch"
          
            if git show-ref --verify --quiet refs/heads/$branch; then
              git checkout $branch
              if git merge-base --is-ancestor $branch $remote_branch; then
                git merge --ff-only $remote_branch
              else
                git rebase $remote_branch || git rebase --abort
              fi
            else
              git checkout -b $branch $remote_branch
            fi
          
            git push --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $branch --force-with-lease
          done

      - name: Sync tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin --tags
